### ISSUE TITLE
Suggestion: Changing any of the "Start Time" fields should reset the "Time" and "Frame" offset fields below

### ISSUE THREAD

**Issue by plipt** [MickWest/sitrec#10]
While investigating satellite flares at a certain time and place I have had the Sitrec simulation unpaused for minutes at a time.

Later when I go to change/tweak the time to observe the changes I have found it confusing to have Sitrec maintain the time offset from the minutes (sometimes upwards of 10 minutes) that I left it running / unpaused even though I selected a new time. As a new user to the app it was not immediately clear to me that there were additional form controls lower in the toolbox that effect the rendered output.

My expectation would be that after changing the starting time settings, the 3d display would render the situation as the exact time I had modified.

I realize there is the ability to have a video imported into the situation, so mayhap there are aspects I am missing that necessitate maintaining a time offset? 

If resetting the offset upon modifying the start time is not desired, maybe make it more clear that the situation is showing the time T+ however many seconds or minutes later?

Thanks for your consideration!

**Comment by MickWest** [comment]
I've had similar issues.  It goes back to Sitrec originally being designed around fixed length videos, typically of a second or so. Perhaps a good solution is to change the UI time control to adjust the _current_ time instead of the start time. So the time offset in the time bar will remain the same, and the UI time will also match the time displayed in the lookView (right view)

**Comment by MickWest** [comment]
As of 1.0.4, the UI now edits the current time (nowTime) instead of startTime, which is automatically created from the current time and the frame position.

**Comment by plipt** [comment]
That works!

Thanks again
