### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by lawrencem** [MickWest/sitrec#25]
**I have followed the instructions in README.md and SitrecNotes.txt. the webserver is nginx and the sitrec root is at the nginx root: /var/www/html/s/sitrec    The production root is /var/www/html/d/sitrec-prod    When I get to the npm run build command, this occurs:**

npm run build

> sitrec@1.0.0 build
> npx webpack --config webpack.dev.js

Sitrec v1.2.0: 24-05-28 13:22 PT
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '../../package.json'
Require stack:
- /var/www/html/s/sitrec/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js
- /var/www/html/s/sitrec/node_modules/webpack/lib/WebpackOptionsApply.js
- /var/www/html/s/sitrec/node_modules/webpack/lib/webpack.js
- /var/www/html/s/sitrec/node_modules/webpack/lib/index.js
- /var/www/html/s/sitrec/node_modules/webpack-cli/lib/webpack-cli.js
- /var/www/html/s/sitrec/node_modules/webpack-cli/lib/bootstrap.js
- /var/www/html/s/sitrec/node_modules/webpack-cli/bin/cli.js
- /var/www/html/s/sitrec/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at version (/var/www/html/s/sitrec/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js:642:21)
    at /var/www/html/s/sitrec/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js:2396:9
    at Hook.eval [as call] (eval at create (/var/www/html/s/sitrec/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:16)
    at Hook.CALL_DELEGATE [as _call] (/var/www/html/s/sitrec/node_modules/tapable/lib/Hook.js:14:14)
    at /var/www/html/s/sitrec/node_modules/webpack/lib/stats/StatsFactory.js:278:7
    at StatsFactory._forEachLevel (/var/www/html/s/sitrec/node_modules/webpack/lib/stats/StatsFactory.js:101:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/s/sitrec/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js',
    '/var/www/html/s/sitrec/node_modules/webpack/lib/WebpackOptionsApply.js',
    '/var/www/html/s/sitrec/node_modules/webpack/lib/webpack.js',
    '/var/www/html/s/sitrec/node_modules/webpack/lib/index.js',
    '/var/www/html/s/sitrec/node_modules/webpack-cli/lib/webpack-cli.js',
    '/var/www/html/s/sitrec/node_modules/webpack-cli/lib/bootstrap.js',
    '/var/www/html/s/sitrec/node_modules/webpack-cli/bin/cli.js',
    '/var/www/html/s/sitrec/node_modules/webpack/bin/webpack.js'
  ]
}

Node.js v20.13.1

**After the error occurs, I searched the directory tree and there is indeed no package.json file anywhere in the tree**

**Comment by lawrencem** [comment]
I had thought that I should be in the webserver tree to run the npm commands, but it turns out that the npm commands are run in a separate tree.

**Comment by MickWest** [comment]
Sorry for the confusing instructions. In hindsight, I should have named the folders differently. I've updated the docs slightly to clarify.

**Comment by lawrencem** [comment]
Thanks!
