### ISSUE TITLE
El Start and El End - FLIR1

### ISSUE THREAD

**Issue by ypeings** [MickWest/sitrec#28]
These parameters do not seem to work (tried in the FLIR1 stitch).

**Comment by MickWest** [comment]
Fixed in https://github.com/MickWest/sitrec/commit/94a937cc40ba27e7d5f91c1251e00e09e38d01d4,  
MB version: Sitrec 1.2.2: 24-05-30 07:16 PT

CNodeMath expressions were not propagating if input nodes changed. Fixed.
