### ISSUE TITLE
Clicking the permalink button fails with a 501 error from rehost.php

### ISSUE THREAD

**Issue by plipt** [MickWest/sitrec#9]
OS Ubuntu 20.04
Browser Chromium Version 121.0.6167.85 no extensions installed

Clicking the permalink button does nothing. After checking the console 3 errors can be seen

> POST https://www.metabunk.org/sitrec/sitrecServer/rehost.php 501 (Not Implemented)
> rehostFilePromise @ index.f38494035140bd9f384f.bundle.js:1
> rehostFile @ index.f38494035140bd9f384f.bundle.js:1
> (anonymous) @ index.f38494035140bd9f384f.bundle.js:1
> rehostDynamicLinks @ index.f38494035140bd9f384f.bundle.js:1
> makeNightSkyURL @ index.f38494035140bd9f384f.bundle.js:1
> (anonymous) @ index.f38494035140bd9f384f.bundle.js:1
> 
> index.f38494035140bd9f384f.bundle.js:1 Error uploading file: Error: Server responded with 501
>     at CRehoster.rehostFilePromise (index.f38494035140bd9f384f.bundle.js:1:291047)
>     at async Promise.all (sitrec/index 0)
> rehostFilePromise @ index.f38494035140bd9f384f.bundle.js:1
> await in rehostFilePromise (async)
> rehostFile @ index.f38494035140bd9f384f.bundle.js:1
> (anonymous) @ index.f38494035140bd9f384f.bundle.js:1
> rehostDynamicLinks @ index.f38494035140bd9f384f.bundle.js:1
> makeNightSkyURL @ index.f38494035140bd9f384f.bundle.js:1
> (anonymous) @ index.f38494035140bd9f384f.bundle.js:1
> 
> index.f38494035140bd9f384f.bundle.js:1 Uncaught (in promise) Error: Upload problem, maybe not logged in?
>     at CRehoster.rehostFilePromise (index.f38494035140bd9f384f.bundle.js:1:291210)
>     at async Promise.all (sitrec/index 0)
> rehostFilePromise @ index.f38494035140bd9f384f.bundle.js:1
> Promise.then (async)
> makeNightSkyURL @ index.f38494035140bd9f384f.bundle.js:1
> (anonymous) @ index.f38494035140bd9f384f.bundle.js:

This error is returned after clicking the permalink button both immediately after sitrec finishes loading or after making some changes.

This error does not occur in Firefox on the same system.

**Comment by MickWest** [comment]
Is this on Metabunk? Or your own server?

It's trying to rehost the current Starlink onto the server. If you are not logged into Metabunk then it will fail. This obviously could be improved.

**Comment by plipt** [comment]
Sorry I should have mentioned, yes this is on Metabunk.

After logging in to my metabunk account, the error goes away, and the URL is updated with the perma link as expected.

Didnt realize that some of the sitrec features are tied into the forum account.

**Comment by MickWest** [comment]
My bad, I should disable that button is not logged in.
